version: "3.8"

services:

  restaurant-service:
    build: ./restaurant-service
    container_name: food-delivery-restaurant
    depends_on:
      - kafka
      - mongo
    ports:
      - "9091:9091"
    environment:
      BAL_CONFIG_VAR_KAFKAURL: kafka:29092
      BAL_CONFIG_VAR_MONGOURL: mongodb://mongo:27017
      
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: food-delivery-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: food-delivery-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  mongo:
    image: mongo:7.0
    container_name: food-delivery-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
